
environmentName: 'non-prod'
server:
  restServicePort: 8081
  ReadTimeout: 5
  WriteTimeout: 15
  IdleTimeout: 20

db:
  Filepath: /guardianlink/
  Databasename: nodea
  
swagger:
  host: localhost:8081